name: Python Code Quality Check (CI)

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Lay code moi nhat tu kho ve may ao
        uses: actions/checkout@v3

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Tu dong chay bo kiem thu Unit Test
        run: |
          python -m unittest test_main.py
